[[events]]
title = "RTC-2 Starfield"
days = 8
hours = 3
minutes = 15
seconds = 0

[[events]]
title = "RTC-2 Slew"
days = 8
hours = 4
minutes = 8
seconds = 0

[[events]]
title = "RTC-2 Burn"
days = 8
hours = 4
minutes = 19
seconds = 10

[[events]]
title = "FD10 Crew Wakeup"
days = 8
hours = 17
minutes = 0
seconds = 0

[[events]]
title = "RTC-3 Starfield"
days = 8
hours = 19
minutes = 15
seconds = 0

[[events]]
title = "RTC-3 Burn"
days = 8
hours = 20
minutes = 29
seconds = 10

[[events]]
title = "FD10 Daily Planning Conference"
days = 8
hours = 20
minutes = 45
seconds = 0

[[events]]
title = "EDL Starfield"
days = 9
hours = 0
minutes = 15
seconds = 0

[[events]]
title = "CM/SM Separation"
days = 9
hours = 0
minutes = 58
seconds = 0

[[events]]
title = "Crew Module Raise Burn"
days = 9
hours = 1
minutes = 2
seconds = 0

[[events]]
title = "Entry Interface"
days = 9
hours = 1
minutes = 18
seconds = 0

[[events]]
title = "Predicted Loss of Signal"
days = 9
hours = 1
minutes = 18
seconds = 20

[[events]]
title = "Predicted Acquisition of Signal"
days = 9
hours = 1
minutes = 24
seconds = 20

[[events]]
title = "Forward Bay Cover Separation (7.6 km/24,000 ft)"
days = 9
hours = 1
minutes = 28
seconds = 10

[[events]]
title = "Drogue Parachutes Deploy (7.6 km/24,000 ft)"
days = 9
hours = 1
minutes = 28
seconds = 13

[[events]]
title = "Pilot and Main Parachutes Deploy"
days = 9
hours = 1
minutes = 29
seconds = 32

[[events]]
title = "Splashdown"
days = 9
hours = 1
minutes = 32
seconds = 0

[[events]]
title = "End of Recovery Ops"
days = 9
hours = 4
minutes = 0
seconds = 0